//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_default : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Pose Pose
        {
            get
            {
                return SteamVR_Actions.default_Pose;
            }
        }
        
        public virtual SteamVR_Action_Skeleton SkeletonLeftHand
        {
            get
            {
                return SteamVR_Actions.default_SkeletonLeftHand;
            }
        }
        
        public virtual SteamVR_Action_Skeleton SkeletonRightHand
        {
            get
            {
                return SteamVR_Actions.default_SkeletonRightHand;
            }
        }
        
        public virtual SteamVR_Action_Boolean HeadsetOnHead
        {
            get
            {
                return SteamVR_Actions.default_HeadsetOnHead;
            }
        }
        
        public virtual SteamVR_Action_Boolean TriggerClick
        {
            get
            {
                return SteamVR_Actions.default_TriggerClick;
            }
        }
        
        public virtual SteamVR_Action_Boolean TriggerHold
        {
            get
            {
                return SteamVR_Actions.default_TriggerHold;
            }
        }
        
        public virtual SteamVR_Action_Boolean SystemClick
        {
            get
            {
                return SteamVR_Actions.default_SystemClick;
            }
        }
        
        public virtual SteamVR_Action_Boolean JoystickTouch
        {
            get
            {
                return SteamVR_Actions.default_JoystickTouch;
            }
        }
        
        public virtual SteamVR_Action_Vector2 JoystickPose
        {
            get
            {
                return SteamVR_Actions.default_JoystickPose;
            }
        }
        
        public virtual SteamVR_Action_Boolean JoystickClick
        {
            get
            {
                return SteamVR_Actions.default_JoystickClick;
            }
        }
        
        public virtual SteamVR_Action_Vector2 TrackpadPose
        {
            get
            {
                return SteamVR_Actions.default_TrackpadPose;
            }
        }
        
        public virtual SteamVR_Action_Boolean TrackpadTouch
        {
            get
            {
                return SteamVR_Actions.default_TrackpadTouch;
            }
        }
        
        public virtual SteamVR_Action_Boolean SqueezeGrip
        {
            get
            {
                return SteamVR_Actions.default_SqueezeGrip;
            }
        }
        
        public virtual SteamVR_Action_Boolean ButtonA
        {
            get
            {
                return SteamVR_Actions.default_ButtonA;
            }
        }
        
        public virtual SteamVR_Action_Boolean ButtonB
        {
            get
            {
                return SteamVR_Actions.default_ButtonB;
            }
        }
        
        public virtual SteamVR_Action_Boolean Pinch
        {
            get
            {
                return SteamVR_Actions.default_Pinch;
            }
        }
        
        public virtual SteamVR_Action_Vibration Haptic
        {
            get
            {
                return SteamVR_Actions.default_Haptic;
            }
        }
    }
}
